### ISSUE TITLE
refactor(`cafs/ipfs`): `DefaultConfig` needs more reliable repo path default

### ISSUE THREAD

**Issue by ramfox** [qri-io/qfs#29]
Currently, we default to a hardcoded `~/.ipfs`

https://github.com/qri-io/qfs/blob/3b8abb5dab05955ca198598e31ef8ffa23a4d54e/cafs/ipfs/config.go#L25-L35

Options:

- default to  `IPFS_PATH` env var, before attempting to find ".ipfs" off the home directory
- However, since we are moving our reliance off of the `IPFS_PATH` and instead expect the ipfs repo to live on the `QRI_PATH`, perhaps that is the better location. But, I'm unsure how much we want to rely on `QRI_PATH`outside of the qri package, or if that is not at all a problem.

**Comment by b5** [comment]
To me this is an example of a _required configuration option_. There isn't really a sensible default, so we shouldn't pick one, and the default configuration should fail if no path is specified. Tests that work these options should create & provide a path

**Comment by ramfox** [comment]
Great.

So the concept of a `DefaultConfig`, specifically for a `FsRepoPath` doesn't make sense. 

Refactoring so that:
- if no repo path is provided, we error
- DefaultConfig now takes a `repoPath string`, filling in the other fields with default configuration.
